### ISSUE TITLE
download dataset

### ISSUE THREAD

**Issue by SabraHashemi** [alitourani/Iranis-dataset#1]
Hi ,first of all, thank you for your works on  persian plates,
 i couldn't find a download link (maybe broken) please guide me, thanks.

**Comment by alitourani** [comment]
Dear sabrabno0,
wish you a good day

I have created this repository to provide public access to the data, but
the authorities refused to let us share it.
Unfortunately, the access to the dataset is restricted, however, we are
trying to find a solution to make it public for research purposes.
The reason is that each license plate belongs to a person and we need valid
permission from the owner of the vehicle to be able to share its image,
which is a tough process!
I will update the mentioned repository if we could find a solution.

Regards,
Ali.
<https://www.linkedin.com/in/alitourani/>

**Comment by sabrabano0** [comment]
thank you, also i want to write your codes in c++ lang, and contribute it
with yours,
if you need a colleague, please let me know, thank you.

**Comment by alitourani** [comment]
Sure. I am looking forward to it.

<https://www.linkedin.com/in/alitourani/>

**Comment by sabrabano0** [comment]
you have deleted your codes. i can't find it anymore.
